# Generated by Django 3.2.9 on 2021-11-06 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome do servico')),
                ('icon', models.FileField(blank=True, help_text='O ícone deve ter formato SVG ou PNG.', upload_to='imagens/servicos/icones', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='ícone')),
                ('description', models.TextField(help_text='Breve descrição do serviço em até 200 caracteres.', max_length=200, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que o serviço será tratado como ativo. Ao invés de excluir o serviço, desmarque isso.', verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_led', to='accounts.member', verbose_name='líder')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', related_query_name='team', to='accounts.Member', verbose_name='membros')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sifhub.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'equipe',
                'verbose_name_plural': 'equipes',
                'ordering': ['service__name'],
            },
        ),
    ]
